<?php
// The content of the article
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <article>
        <div class="centered">
            <div class="title">A SPECIAL DECONSTRUCTION OF THE ONTOLOGICAL STRUCTURE OF THE REALITY INFORMATION SYSTEM PROGRAM</div>
            <div class="subtitle">PART ONE: MONITORING DEEP STATES OF REALITY AND DISSECTING THE COMPLEX INFORMATIONAL IMPACT ON THE COLLECTIVE HUMAN UNCONSCIOUS</div>
            <div class="section">1.1. A PRELUDE TO A VARIOUS MYSTICAL VISION</div>
        </div>
        <p>It is not only religious systems and beliefs that take over a large part of our absurd and superficial human life and traditions, rather, there is a much greater doctrine that takes over us completely and controls the system of our existence and our mental vision intertwined with the complexities of the relative outside world, it is without a doubt the doctrine of information system which is intersect and weaves certain vibrations and levels of energy onto our human mind and it is essentially formed the external reality in a complex way that relies on its own programming.</p>
        <p>We are somehow subject to that part that we cannot perceive and our relative consciousness cannot comprehend its upper field that transcends our biocompatible human sphere, and our human sphere, subject to a certain biological, chemical and physical coordination, has contributed to the disruption of the inner, open borders of the human self. We and others in this world interact with super-programmed information system in forms that we cannot truly absorb at the moment as a result of our low level of human consciousness and our low level of perception in dealing with the depths of reality and our view of the depths of reality.</p>
        <p>We are dealing with this information system without realizing that we are dealing with, and we are unable to comprehend the possibility that this system we are dealing with and to which we are essentially subject is subject to superior overhead programming that we cannot perceive and analyses within the level of limitations of human consciousness associated with the earth reality system, and within this information system the whole system of data were stored. This information system is represented by the system of the universe, and there are broad lines that form the basis of this accurate information system whose effects flow through all parts of reality, and thus its effects flow through all parts of our human life system.</p>
        <p>The total information system to which we are subject has contributed to grafting the human mind and moving its perception vision through time and ages, until this system contributed to creating an evolutionary cycle exacerbated by its successive consequences on the mind until this cycle worked on creating an integrated programming for a real world that exists in the belief of the human mind. More clearly, that information system which created us and flowing through us creates a specific real world that we interact with, in other words, the deep basic real world does not exist in the way imagined by our human mind which is subject to that programmed level and is highly influenced by this information system that controls the parts of our existence and which that contributed to reflected our vision to create us certain relativistic stereotype in our mind, and thus we have a mental vision that is truncated and fragmented at the same time, and it is not total and not completely true, but only in a relative way in which it contradicts the deep inner reality of the ontological structure in which we are present.</p>
        <p>The human race in general tends and walks within a stereotypical programmed cycle that is not free from its constraints, that is, we are walking but not completely consciously in this reality as if we are heading in an absurd manner to make the absurd meaning of the things and meanings around us and we ourselves are possessed by that system that disrupts our deep inner vision of deep inner existential reality. Our real system, which is basically not the real deep reality system, is a very thorny information system that cannot be absorbed in a real and deep way, as many people thought, because it basically represents part of the total ontological system subject to pre-programming determined by a higher field based on creation and innovation that exists behind the structure of our existential system and therefore behind our cosmic order.</p>
        <p>Information formed the existential program for human life subject to its closed restrictions, what humanity has done since ancient times is to exploit reality to invest information that contributed in one way or another to building a specific system that determined the directions of human consciousness that became subject to that illusory relative cycle through which we lived and live our trivial life on earth. The invention of writing since ancient times and what the ancient texts provided give a real dimension for us as human beings to the sequence of human informational reality and its successive and conflicting impact on us.</p>
        <p>And step by step, we had make up a specific information program on the ground level that works to cover and analyses things and creatures according to its specific human-created coordination, that is, a specific information program that does not cover what must be covered on the deep realistic level and does not look through the level that must be looked through, which is the level outside the normal relative range of human consciousness, but it's only suffices for specific relative explanations in the structure of the external reality. Thus, our mental vision program that was directed by that information system controls our real human movement and directs our consciousness within superficial areas that deal with the crusts of reality and contradict with the deep inner essence that must be looked through in this reality, as if we have completely unreal roots that we cannot cut out, as they take over our unconscious frequency field, which includes the psychological field of the subconscious of the self.</p>
        <p>There are many esoteric and inner matters and ideas that emerged in ancient times on earth and were hidden in our present time, looking through the depths of ancient times and through the dimensions of the pagan esoteric nature is extremely important, in addition to keep our connection with the reality of the technological movement in which we live, there is nothing clear in this world... everything goes vaguely, even if you feel otherwise, o human being stuck in the shadow of the illusory system, you are inevitably wrong because you are subject to that illusory system that includes your vision system that programmed at what it is, which (vision or perception system programmed) attacks every thought or mind or logic opposing it even if for its absent interest within the illusory system itself, it is as if the mind has become like a closed machine defined by its own programming and forgotten that it possesses a deep and super inner consciousness known as human consciousness that has been removed and locking its real influence away from our reality through dilated processes that affected and affecting the human mind through times and ages on earth.</p>
        <p>The religious system with its various pluralities and models, the political system with its various pluralities and models, and even the modern materialistic scientific system in itself have all become, intentionally or unintentionally, working to subject the human mind to a reductive and impoverished programmatic system that lacks its true powers... and thus we are gradually moving away from the deep points and lines of the true reality and the truth itself. Ancient ages or times have been referred previously in this context for a reason indicate to differences in perceptions mental orientations of the humans between ages and times, because perceptions mental orientations of the humans is main thing in our various orientation here. What existed in that times and what was written in their civilizations many of it may contradicts the belief of humans who live within their current closed mental limits... that is, within the limits of the political, religious, scientific, and materialistic system that dominates the current reality of human society. The existence information system has the utmost precision that the mind cannot imagine and this precision determined within parts of the mind working system and the theatre of the human subconscious.</p>
    </article>
</body>
</html>
